language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

matrix:
  - php: 5.5
    env: COMPOSER_FLAGS="--prefer-lowest"

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script: phpunit --coverage-text
